title: ROXANNE | ROSJava
logo: /assets/img/logo.png
description: ROXANE ROSJava Package
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

defaults:
  # docs
  - scope:
    path: ""
    type: docs
  values: 
    sidebar: 
      nav: "docs"
